language: ruby
rvm:
  - 2.1.2
install: gem install bundler
script:
  - travis_retry bundle install
  - bin/rake db:create
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - cucumber
  - bin/rails s -d
  - npm install
  - npm -g install karma-cli
  - karma start spec/javascripts/karma.conf.js